service: rh-create-passenger

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DYNAMODB_TABLE: 'passenger'
    PASSENGER_ENDPOINT_PATH: 'https://circulo-staging.ridehealth.com/rest/v1/passenger'
    RH_USER: 'admin@ridehealth.com'
    RH_PASS: 'test'
    BATCH_RUN_NO: 3 #This should increase as we scale
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}'
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
      Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/*'
  region: us-east-2
  lambdaHashingVersion: 20201221

functions:
  createPassenger:
    handler: handler.createPassenger
    events:
      - schedule:
          rate: rate(60 minutes)
          enabled: false
    #events:
    #- schedule: cron(0/58 * ? * MON-FRI *)
